CREATE USER Azad_Arousha WITH PASSWORD 'azad2000Arousha';
GRANT CONNECT ON DATABASE postgres TO Azad_Arousha;
GRANT USAGE ON SCHEMA public TO Azad_Arousha;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO Azad_Arousha;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO Azad_Arousha;